# Stages of piepline, should match with stage tag inside each job.
stages:
  - maven-build
  - maven-test
  - autodeploy
  - libgdx-build
  - libgdx-test

  # tags: "maven_tag" should match tag name provided in runner
maven-build:
  stage: maven-build
  tags:
    - maven_tag
  script:
    - cd Backend/src/API/testAPI/test
    - mvn package -B

maven-test:
  stage: maven-test
  tags:
    - maven_tag
  script:
    - cd Backend/src/API/testAPI/test
    - mvn test
  artifacts:
    paths:
      - spring/target/*.jar

autoDeploy:
  stage: autodeploy
  tags:
    - maven_tag
  script:
    - cd Backend/src/API/testAPI/test
    - mvn package
    - sudo mv target/*.jar target/web-demo.jar
    - sudo systemctl stop system-web-demo
    - sudo systemctl start system-web-demo

libgdx-build:
  image: javiersantos/android-ci:latest
  stage: libgdx-build
  before_script:
    - export GRADLE_USER_HOME='pwd'/.gradle
  tags:
    - libgdx_tag
  script:
    - chmod +x ./Frontend/LibgdxCnDT/gradlew
    - cd Frontend/LibgdxCnDT
    - gradlew assemble

libgdx-test:
  image: javiersantos/android-ci:latest
  stage: libgdx-test
  before_script:
    - export GRADLE_USER_HOME='pwd'/.gradle
    - chmod +x ./Frontend/LibgdxCnDT/gradlew
  tags:
    - libgdx_tag
  script:
    - cd Frontend/LibgdxCnDT
    - gradlew test
